---
title: "Data load"
author: "Anthony Staines"
date: "28/01/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
rm(list = ls())
library(lubridate)
library(gt)
library(kableExtra)
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

# Load files

There are data files for each year from 2013 to October 2020. The rest of 2020 is awaited.

```{r load}
D2013 <- readxl::read_excel('data/2013 head injuries.xls')
D2014 <- readxl::read_excel('data/2014 head injuries.xls')
D2015 <- readxl::read_excel('data/2015 head injuries.xls')
D2016 <- readxl::read_excel('data/2016 head injuries.xls')
D2017 <- readxl::read_excel('data/2017 head injuries.xls')
D2018 <- readxl::read_excel('data/2018 head injuries.xls')
D2019 <- readxl::read_excel('data/2019 head injuries.xls')
#D2020 <- readxl::read_excel('data/2020 head injuries.xls')
names(D2013)
names(D2019)

vtable::vt(D2013)
vtable::vt(D2014)
vtable::vt(D2015)
vtable::vt(D2016)
vtable::vt(D2017)
vtable::vt(D2018)
vtable::vt(D2019)




TBI <- D2019 %>% rbind(D2018) %>% rbind(D2017) %>% rbind(D2016) %>% rbind(D2015) %>% rbind(D2014) %>% rbind(D2013)
rm(D2013,D2014,D2015,D2016,D2017,D2018,D2019)

```

# 2019
 Fix the variable names
```{r FixNames, echo=FALSE}

# Spaces to _
# - to _
# Remove _(Y/N)
# Remove brackets
# / to or

NAMES <- as_tibble(names(TBI))
NAMES %>% write_csv('data/names.csv') # Manually altered
NAMES <- read_csv('data/names_revised.csv')# %>% select(-X1)

names(TBI) <- NAMES$NewName  
```

Fix the variable types
```{r FixTypes}
table(NAMES$NewName,NAMES$Type)

#Numbers
Numbers <- NAMES %>% filter(Type == 'Numeric') %>% select(NewName)
  COLS <- Numbers$NewName
TBIt <- TBI %>%
  mutate(across(all_of(COLS), as.numeric))
  rm(Numbers)

#Dates
Dates <- NAMES%>% filter(Type == 'Date') %>% select(NewName)
  COLS <- Dates$NewName
TBIt <- TBIt %>%
  mutate(across(all_of(COLS), as_date))
  rm(Dates)

vtable::vt(TBIt)
warnings()

TBI <- TBIt
rm(TBIt, COLS, NAMES)
```

# Add new variables

```{r AddNew}
#Correctly ordered age groups
TBI <- TBI %>%
  mutate(AgeGrp = as_factor(Age_by_5_year)) %>%
  mutate(AgeGrp = fct_reorder(AgeGrp, Age_by_1_year))# %>%
#  mutate(AgeGrp = fct_relevel(AgeGrp, "5-9", after=1)) %>%
#  mutate(AgeGrp = fct_relevel(AgeGrp, "100-104", after=Inf))
TBI %>% select(AgeGrp) %>% group_by(AgeGrp) %>% summarise(N = n())

```

# Basic tables

```{r}

Gender <- gt(data=TBI %>%
               select(Gender) %>%
               group_by(Gender) %>%
               summarise(N = n())
             ) %>%
  tab_header(
    title = "Gender",
    subtitle = "Only Male and Female are recorded"
  )

Gender

Age <- gt(data=TBI %>%
            select(AgeGrp) %>%
            group_by(AgeGrp) %>%
            summarise(N = n())
             ) %>%
  tab_header(
    title = "Age (5 year age groups)",
    subtitle = "All S00-S09 admissions"
  )

Age

Source <- gt(data=TBI %>%
            select(Admission_source) %>%
            group_by(Admission_source) %>%
            summarise(N = n())
             ) %>%
  tab_header(
    title = "Source of admission",
    subtitle = "All S00-S09 admissions"
  )

Source

Type <- gt(data=TBI %>%
            select(Admission_type) %>%
            group_by(Admission_type) %>%
            summarise(N = n())
             ) %>%
  tab_header(
    title = "Type of admission",
    subtitle = "All S00-S09 admissions"
  )

Type

Destination <- gt(data=TBI %>%
            select(Discharge_destination) %>%
            group_by(Discharge_destination) %>%
            summarise(N = n())
             ) %>%
  tab_header(
    title = "Discharge destination",
    subtitle = "All S00-S09 admissions"
  )

Destination

Group.db <- TBI %>%
  select(Medical_card, NTPF, Public_or_private) %>%
  group_by(Medical_card, NTPF, Public_or_private) %>%
  summarise(N=n())

Group.db %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria")

```

# Basic plots

```{r}
Daily_Admissions <- TBI %>%
  select(Admission_date) %>%
  group_by(Admission_date) %>%
  summarise(N = n()) %>%
  mutate(Day_of_week = wday(Admission_date,
                            label = TRUE)) %>%
  mutate(Weekend = ifelse((Day_of_week %in% c('Sat','Sun')),1,0))
  
str(Daily_Admissions)

ggplot(Daily_Admissions, aes(x=Admission_date, y=N)) +
  geom_point(aes(colour=Weekend)) +
  geom_smooth()  +
  geom_line(alpha=0.2,colour='pink')

```
